name: AQIP Frontend CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Frontend
        uses: ./.github/actions/build-frontend
